### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by MagaCraft202** [JohnEBoyBaby/i.Q#1]
So, I came across this repository while searching for an easy way of querying PCI class codes, subclasses, and program interfaces.
My question is: wtf is this?

**Comment by JohnEBoyBaby** [comment]
DEAR BIG COLD-BLOODED DUMMY,

STEP RIGHT UP ... Step Right Up ... step right up ...

THE NEXT T.C.A. TRUTH Checking Angel will be with you shortly ... PLEASE DO ... STAY TUNED ... SAME QAT TIME ... SAME QAT CHANNEL ... YOU JUST MIGHT "LEARN" SOMETHING 'son' ... MAKE IT COUNT 'son' ... MCPM.

TRUTH
